# Generated by Django 4.2.1 on 2023-05-21 22:47

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nota', models.FloatField(default=0.0, validators=[base.models.validate_float_range])),
                ('ano', models.IntegerField()),
                ('sinopse', models.TextField(blank=True)),
                ('genero', models.CharField(max_length=500)),
            ],
        ),
    ]
